<?php
session_start();
if(!isset($_SESSION['aktueller_benutzer'])) {
    die('Bitte zuerst <a href="index.php">einloggen</a>');
}
$user = $_SESSION['aktueller_benutzer'];
?>

<!doctype html>
	<html lang="de">
	<head>
		<meta charset="utf-8"/>
		<link rel="stylesheet" href="quiz.css">
		<title>Hilfe</title>
	</head>

	<body>
	<h1>Quizlein</h1>
	<circle-button><a type="button" class="circle-button" href="profil.php" style="color:white" ><?php echo $user ?></a></circle-button>
		<div id=startLinks>
			<button><a type="button" class="button" href="startseite.php">Startseite</a></button>
			<button><a type="button" class="button" href="fragenset.php">Fragen beantworten</a></button>
			<button><a type="button" class="button" href="eigene_fragen.php">Eigene Fragen</a></button>
			<button><a type="button" class="button" href="spielerliste.php">Spielerliste</a></button>
			<button><a type="button" class="button" href="verwaltung.php">Verwaltung</a></button>
			<button><a type="button" class="button" href="hilfe.php">Hilfe</a></button>
			<button><a type="button" class="button" href="index.php">Abmelden</a></button>
		</div>
		</br>
		</br>
		</br>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed arcu non odio euismod lacinia at. Condimentum lacinia quis vel eros donec ac odio. Vitae congue eu consequat ac felis donec et odio pellentesque. Quam elementum pulvinar etiam non quam. Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Aliquam sem fringilla ut morbi tincidunt augue. Luctus accumsan tortor posuere ac ut consequat semper viverra. Netus et malesuada fames ac turpis egestas sed. Sed lectus vestibulum mattis ullamcorper velit. Ut consequat semper viverra nam libero justo. Mauris rhoncus aenean vel elit. Neque sodales ut etiam sit amet. In nibh mauris cursus mattis molestie a iaculis. Diam volutpat commodo sed egestas egestas fringilla phasellus. In hac habitasse platea dictumst quisque sagittis purus. Consectetur a erat nam at lectus urna. Pulvinar elementum integer enim neque volutpat ac tincidunt. Molestie a iaculis at erat pellentesque.

		Feugiat nisl pretium fusce id velit ut tortor pretium. Aenean pharetra magna ac placerat vestibulum lectus mauris. Est ante in nibh mauris cursus mattis molestie a iaculis. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Rhoncus dolor purus non enim praesent elementum facilisis leo vel. A diam maecenas sed enim ut sem viverra. Mauris in aliquam sem fringilla. Blandit turpis cursus in hac habitasse platea. Ante in nibh mauris cursus mattis. Quis blandit turpis cursus in hac habitasse. Fringilla urna porttitor rhoncus dolor purus non enim. Pellentesque massa placerat duis ultricies lacus. Convallis posuere morbi leo urna molestie. Habitant morbi tristique senectus et netus et malesuada. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Tincidunt vitae semper quis lectus nulla at. Sed enim ut sem viverra aliquet eget sit amet. Id diam maecenas ultricies mi eget. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat.

		Arcu non odio euismod lacinia. Faucibus et molestie ac feugiat sed lectus. Libero enim sed faucibus turpis in eu mi bibendum neque. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Nibh tellus molestie nunc non blandit massa. Leo integer malesuada nunc vel risus commodo. Eget magna fermentum iaculis eu non diam phasellus vestibulum. Tristique senectus et netus et. Elementum sagittis vitae et leo duis ut diam. Ullamcorper sit amet risus nullam eget felis. Egestas purus viverra accumsan in. Sit amet massa vitae tortor condimentum. Semper feugiat nibh sed pulvinar proin gravida hendrerit. Consectetur libero id faucibus nisl tincidunt eget. Urna molestie at elementum eu. Laoreet non curabitur gravida arcu ac tortor dignissim convallis aenean. Aliquam faucibus purus in massa tempor nec feugiat nisl. Tellus in metus vulputate eu scelerisque felis imperdiet proin. Volutpat lacus laoreet non curabitur gravida. Enim sit amet venenatis urna.

		Tempus egestas sed sed risus pretium quam vulputate dignissim. Fermentum leo vel orci porta non pulvinar neque laoreet. Maecenas sed enim ut sem viverra. Pulvinar sapien et ligula ullamcorper malesuada proin libero. Scelerisque in dictum non consectetur a erat. Nibh ipsum consequat nisl vel pretium lectus quam. Orci sagittis eu volutpat odio. Mattis nunc sed blandit libero volutpat sed cras. Est velit egestas dui id ornare. Porta non pulvinar neque laoreet suspendisse interdum consectetur libero id. Odio aenean sed adipiscing diam donec adipiscing tristique. Amet porttitor eget dolor morbi non. Morbi tristique senectus et netus. In ornare quam viverra orci sagittis eu volutpat. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Et odio pellentesque diam volutpat commodo sed egestas. Venenatis cras sed felis eget velit.

		Enim blandit volutpat maecenas volutpat blandit aliquam etiam. Est sit amet facilisis magna etiam tempor orci eu. Vitae suscipit tellus mauris a diam maecenas sed enim. Magna fermentum iaculis eu non. Velit scelerisque in dictum non consectetur a erat nam at. Convallis posuere morbi leo urna molestie at elementum. Amet massa vitae tortor condimentum lacinia quis. Risus feugiat in ante metus dictum at. Amet consectetur adipiscing elit ut aliquam purus sit. Placerat orci nulla pellentesque dignissim enim sit amet. Natoque penatibus et magnis dis. Sit amet mauris commodo quis imperdiet massa tincidunt. In metus vulputate eu scelerisque felis imperdiet proin fermentum. Nunc non blandit massa enim nec dui nunc mattis enim. Aliquam ut porttitor leo a diam sollicitudin tempor id. A diam sollicitudin tempor id eu nisl nunc. Neque laoreet suspendisse interdum consectetur.
		
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit. Luctus accumsan tortor posuere ac ut consequat. Odio eu feugiat pretium nibh ipsum consequat. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Purus viverra accumsan in nisl nisi. Purus gravida quis blandit turpis cursus in hac habitasse. Eros in cursus turpis massa tincidunt dui ut. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Interdum varius sit amet mattis vulputate enim nulla aliquet. Ipsum dolor sit amet consectetur adipiscing elit. Aliquam malesuada bibendum arcu vitae. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer.

	Nibh venenatis cras sed felis eget velit aliquet sagittis. Fusce ut placerat orci nulla pellentesque dignissim enim sit. Odio morbi quis commodo odio aenean. At consectetur lorem donec massa sapien faucibus et. Aenean euismod elementum nisi quis eleifend quam. Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Vel facilisis volutpat est velit egestas dui id ornare. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Tincidunt arcu non sodales neque sodales ut. Accumsan lacus vel facilisis volutpat est velit. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar.

	At ultrices mi tempus imperdiet nulla malesuada. Et leo duis ut diam quam nulla porttitor massa id. Ornare aenean euismod elementum nisi quis eleifend. Commodo odio aenean sed adipiscing diam donec adipiscing. Tempor orci dapibus ultrices in iaculis nunc sed. Nam aliquam sem et tortor consequat id. Euismod nisi porta lorem mollis. Cum sociis natoque penatibus et magnis dis parturient. In iaculis nunc sed augue lacus viverra vitae congue eu. Sed enim ut sem viverra aliquet eget sit amet. Leo vel orci porta non pulvinar neque laoreet suspendisse. Ullamcorper eget nulla facilisi etiam dignissim diam. Scelerisque in dictum non consectetur a. Amet cursus sit amet dictum sit amet. Risus ultricies tristique nulla aliquet enim tortor at auctor. Id consectetur purus ut faucibus. Varius quam quisque id diam. Diam in arcu cursus euismod quis viverra nibh. Aliquam sem et tortor consequat id porta nibh.

	In est ante in nibh mauris. Diam vel quam elementum pulvinar etiam non quam. Laoreet id donec ultrices tincidunt arcu non sodales neque. Eget est lorem ipsum dolor sit. Nunc sed id semper risus in. Varius duis at consectetur lorem donec massa sapien faucibus et. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Iaculis eu non diam phasellus vestibulum lorem sed risus. Porta lorem mollis aliquam ut porttitor leo a diam sollicitudin. Sagittis eu volutpat odio facilisis mauris sit amet massa vitae. Enim sed faucibus turpis in. Dis parturient montes nascetur ridiculus mus mauris. Integer feugiat scelerisque varius morbi.

	Sed blandit libero volutpat sed cras ornare arcu. Ultrices dui sapien eget mi proin sed. Amet tellus cras adipiscing enim eu turpis egestas pretium aenean. Risus at ultrices mi tempus. Vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Sagittis aliquam malesuada bibendum arcu vitae. Cras fermentum odio eu feugiat pretium. Dictumst quisque sagittis purus sit amet volutpat consequat. Sodales neque sodales ut etiam. Sed sed risus pretium quam vulputate. Rutrum quisque non tellus orci ac. Pretium vulputate sapien nec sagittis. Iaculis at erat pellentesque adipiscing commodo elit. Cursus mattis molestie a iaculis at erat pellentesque adipiscing commodo. Aliquam etiam erat velit scelerisque in dictum. Tincidunt dui ut ornare lectus sit amet est placerat. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Amet consectetur adipiscing elit ut aliquam.
	
	Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sagittis aliquam malesuada bibendum arcu. Varius quam quisque id diam vel. Orci porta non pulvinar neque laoreet suspendisse. Mattis molestie a iaculis at erat pellentesque adipiscing commodo elit. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Ullamcorper morbi tincidunt ornare massa eget. Dui nunc mattis enim ut tellus. Sed pulvinar proin gravida hendrerit lectus a. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Libero nunc consequat interdum varius sit amet mattis vulputate enim. Sed viverra tellus in hac habitasse platea dictumst. Viverra orci sagittis eu volutpat odio facilisis mauris sit. Sit amet massa vitae tortor condimentum lacinia. Pellentesque habitant morbi tristique senectus et netus et. Nibh cras pulvinar mattis nunc sed blandit libero volutpat. Posuere ac ut consequat semper. Velit egestas dui id ornare arcu odio ut. Nulla porttitor massa id neque. Vivamus at augue eget arcu dictum varius.

	Tellus mauris a diam maecenas sed enim ut sem viverra. Ullamcorper malesuada proin libero nunc consequat interdum varius sit amet. Et tortor at risus viverra adipiscing at. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Sapien eget mi proin sed libero enim sed. Facilisis gravida neque convallis a. Lorem ipsum dolor sit amet consectetur adipiscing. Id volutpat lacus laoreet non curabitur. Tellus at urna condimentum mattis. Sed euismod nisi porta lorem. Eu facilisis sed odio morbi quis commodo odio. Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio eu. Magna fringilla urna porttitor rhoncus. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Volutpat consequat mauris nunc congue. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Risus feugiat in ante metus. Cras tincidunt lobortis feugiat vivamus at augue eget arcu dictum.

	Euismod in pellentesque massa placerat duis. Et pharetra pharetra massa massa ultricies. Quisque sagittis purus sit amet volutpat consequat mauris nunc congue. Lacus luctus accumsan tortor posuere ac ut consequat semper. Cras fermentum odio eu feugiat pretium. Lorem donec massa sapien faucibus. Ut aliquam purus sit amet luctus. Duis convallis convallis tellus id interdum velit laoreet id. Nulla facilisi morbi tempus iaculis. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Leo urna molestie at elementum eu facilisis sed odio. Eros donec ac odio tempor orci dapibus. Sed vulputate mi sit amet mauris commodo quis imperdiet massa. Dolor sit amet consectetur adipiscing. Porttitor eget dolor morbi non arcu risus quis varius.

	Aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Nec feugiat in fermentum posuere urna. Phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Leo duis ut diam quam nulla porttitor. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Nisl condimentum id venenatis a. Dignissim suspendisse in est ante in. Iaculis eu non diam phasellus vestibulum lorem. Orci eu lobortis elementum nibh tellus molestie nunc non. Non diam phasellus vestibulum lorem sed risus. Ac orci phasellus egestas tellus. Pretium nibh ipsum consequat nisl vel pretium lectus quam. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Euismod in pellentesque massa placerat duis ultricies lacus sed turpis. Accumsan in nisl nisi scelerisque eu ultrices vitae. Ac placerat vestibulum lectus mauris ultrices eros in cursus. Egestas tellus rutrum tellus pellentesque eu tincidunt. Hendrerit gravida rutrum quisque non tellus. At quis risus sed vulputate odio ut enim.

	Posuere sollicitudin aliquam ultrices sagittis orci a. Proin libero nunc consequat interdum varius sit. Aliquet enim tortor at auctor urna. Velit ut tortor pretium viverra suspendisse potenti. Natoque penatibus et magnis dis parturient montes nascetur ridiculus. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis. Scelerisque viverra mauris in aliquam sem. Lorem sed risus ultricies tristique nulla aliquet enim. Aliquet nibh praesent tristique magna sit amet purus gravida quis. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Enim sit amet venenatis urna cursus eget nunc scelerisque.
	
	Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis risus sed vulputate odio. Nisl tincidunt eget nullam non nisi est sit. Dapibus ultrices in iaculis nunc sed augue lacus. Leo vel fringilla est ullamcorper eget nulla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Nulla at volutpat diam ut venenatis tellus. Ac felis donec et odio pellentesque diam volutpat. Volutpat consequat mauris nunc congue nisi vitae suscipit. Ut tristique et egestas quis. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. At in tellus integer feugiat scelerisque varius morbi enim. Sit amet massa vitae tortor condimentum lacinia quis. Ut tortor pretium viverra suspendisse. Scelerisque purus semper eget duis at tellus. Amet dictum sit amet justo donec enim diam vulputate. Augue interdum velit euismod in pellentesque massa placerat. Eget magna fermentum iaculis eu non diam phasellus vestibulum lorem. Tincidunt vitae semper quis lectus nulla at volutpat diam.

	Orci sagittis eu volutpat odio facilisis mauris sit. Feugiat pretium nibh ipsum consequat. Nec ullamcorper sit amet risus. Volutpat sed cras ornare arcu dui vivamus. Dictum varius duis at consectetur lorem donec massa. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Urna nunc id cursus metus aliquam eleifend. Quis viverra nibh cras pulvinar mattis nunc sed blandit libero. Eu feugiat pretium nibh ipsum consequat nisl vel. Donec adipiscing tristique risus nec feugiat in fermentum posuere.

	Sed velit dignissim sodales ut eu. Blandit aliquam etiam erat velit scelerisque in dictum non consectetur. Feugiat in ante metus dictum at tempor commodo. Dictum at tempor commodo ullamcorper a lacus. Augue interdum velit euismod in pellentesque massa. Feugiat vivamus at augue eget arcu dictum varius. Pharetra et ultrices neque ornare aenean euismod elementum. Pretium lectus quam id leo in vitae. Et ultrices neque ornare aenean euismod elementum. Est sit amet facilisis magna etiam tempor orci. In vitae turpis massa sed elementum tempus egestas sed sed. Nullam ac tortor vitae purus faucibus. Est placerat in egestas erat imperdiet sed euismod. Sed faucibus turpis in eu mi. Et netus et malesuada fames ac.

	Enim nec dui nunc mattis enim ut tellus elementum. At quis risus sed vulputate odio ut enim. Ut placerat orci nulla pellentesque dignissim enim sit amet. Ipsum nunc aliquet bibendum enim. Egestas sed sed risus pretium quam vulputate. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Purus in mollis nunc sed. Amet tellus cras adipiscing enim eu turpis. Morbi tincidunt augue interdum velit euismod in pellentesque massa. Tellus in metus vulputate eu. Egestas erat imperdiet sed euismod nisi. Quis vel eros donec ac odio. Lacus sed viverra tellus in hac habitasse. Mauris ultrices eros in cursus turpis massa. Etiam dignissim diam quis enim lobortis scelerisque. Aenean vel elit scelerisque mauris pellentesque. Dui vivamus arcu felis bibendum ut. Urna duis convallis convallis tellus id interdum. Nullam non nisi est sit amet facilisis magna etiam.

	Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Amet aliquam id diam maecenas ultricies mi. Ullamcorper eget nulla facilisi etiam. Nunc sed velit dignissim sodales. Amet tellus cras adipiscing enim eu turpis. Vestibulum sed arcu non odio. Fames ac turpis egestas integer eget aliquet nibh. Pellentesque dignissim enim sit amet venenatis urna. Varius quam quisque id diam vel quam elementum pulvinar etiam. Eget nullam non nisi est sit amet. Cras semper auctor neque vitae. Ornare suspendisse sed nisi lacus sed viverra tellus in. Sed vulputate mi sit amet mauris commodo quis. Pretium lectus quam id leo in vitae turpis. Vel elit scelerisque mauris pellentesque pulvinar.
	</br>
	Hoffe das hat geholfen
		
	</body>

</html>
